import Head from 'next/head'
import Nav from '../components/nav.js'
import Banner from '../components/banner.js'
import Vision from '../components/vision.js'
import Strength from '../components/strength.js'
import Service from '../components/service.js'
import ServiceResponsive from '../components/serviceResponsive.js'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Nav />
      <Banner />
      <Vision />
      <div className='hidden lg:block'>
        <Service />
      </div>
      <div className='md:hidden'>

      <ServiceResponsive />
      </div>
      <Strength />
    </div>
  )
}
